### ISSUE TITLE
Validate Dimensions Range Mis-Typed

### ISSUE THREAD

**Issue by curreta** [erikdahlstrand/shrine-rails-example#20]
The dimensions validation range on this line: https://github.com/erikdahlstrand/shrine-rails-example/blob/master/app/uploaders/image_uploader.rb#L18

should be:

```validate_dimensions [0..5000, 0..5000]```

instead of 

```validate_dimensions [0..0, 5000..5000]```

**Comment by janko** [comment]
Oops, thanks for the report, will push a fix.
