### ISSUE TITLE
Will progress bar work with this kind of approach?

### ISSUE THREAD

**Issue by alltechfreaks** [erikdahlstrand/shrine-rails-example#3]
I am trying to add a progress bar on top of this file upload example. But cant figure out with the example setup

    $(function() {
      $('[type=file]').fileupload({
        add: function(e, data) {
          $.getJSON('/attachments/images/cache/presign', function(result) {
            data.formData = result['fields'];
            data.url = result['url'];
            data.submit();
          });
        },
    
        done: function(e, data) {
          var image = {
            id: data.formData.key.match(/\w+$/)[0],
            storage: 'cache',
            metadata: {
              size:      data.files[0].size,
              filename:  data.files[0].name,
              mime_type: data.files[0].type
            }
          }
    
          data = {photo: {image: JSON.stringify(image)}}
          $.ajax("#{@listing.id}/photos", {method: 'POST', data: data, dataType: 'script'})
        }
      });
    });
    
    
As all here is the done callback I cant figure out how to get the progress event and error events?

**Comment by janko-m** [comment]
The application uses the [jQuery-File-Upload](https://github.com/blueimp/jQuery-File-Upload) JavaScript library, so you can look at the [documentation](https://github.com/blueimp/jQuery-File-Upload/wiki/Options#progress).

**Comment by janko-m** [comment]
To be explicit, the following should work:

```js
$(function() {
  $('[type=file]').fileupload({
    add: function(e, data) { /* ... */ },
    done: function(e, data) { /* ... */ },
    progress: function(e, data) {
      var progress = parseInt(data.loaded / data.total * 100, 10);
      // update the progress bar with this variable
    }
  });
});
```

That's awesome about using a mature popular JS framework for file uploads, they probably support anything that you'll ever want :)
