### ISSUE TITLE
Module build fails

### ISSUE THREAD

**Issue by crashspringfield** [erikdahlstrand/shrine-rails-example#33]
I tried following the instructions to get this to build, but have the following error:

    bootstrap:83 Uncaught Error: Module build failed (from ./node_modules/babel-loader/lib/index.js):
    Error: Package exports for '/home/matthew/projects/shrine-rails-example/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath

**Comment by crashspringfield** [comment]
Looks like this is an issue with Babel: 
[https://github.com/babel/babel/issues/10997](https://github.com/babel/babel/issues/10997)

And from [this response](https://stackoverflow.com/questions/59706130/error-package-exports-for-path-to-project-folder-node-modules-babel-helper-c) the Rails solution requires updating `package.json` to specify a Node version that isn't 13

    "engines": {
       "node": "12.14.1"
    }

I'd be down to branch and open a MR with that update.

**Comment by janko** [comment]
Sounds good to me, thanks 👍

**Comment by loumarven** [comment]
I also had to do the following:
`nvm install v12.14.1`
`nvm use v12.14.1`
`rm -rf node_modules`
`rm -f yarn.lock`

**Comment by janko** [comment]
I've upgraded webpacker and related pakcages, and that seems to have fixed the error.
