### ISSUE TITLE
Missing something?

### ISSUE THREAD

**Issue by jegodwin** [erikdahlstrand/shrine-rails-example#4]
I've setup everything as the Readme instructed (Bundled gems, setup `.env`, and migrated), but when i run the app and try to upload an image, it does nothing? I'm not getting JS errors in the console either. I just click 'choose files' select a .jpg image, and then nothing. (below is an image of what I see).

I doubt it's related, but I am running Ruby 2.3.0?

Pic:
![screen shot 2016-01-11 at 9 12 56 am](https://cloud.githubusercontent.com/assets/2034140/12235797/0b5ee20c-b844-11e5-908f-3fa580a385b7.png)

**Comment by janko-m** [comment]
When you attach a file, it is first uploaded in the background to S3, and afterwards it should appear on the screen (I would accept a PR which adds a progress bar). Maybe the file was too big or the connection slow? It works for me on 2.3.0.

**Comment by jegodwin** [comment]
Hmmm, strange. I've tried a few different size images and never got it to work. After I select an image, there is nothing happening in background, and the image never loads.

It's probably something I'm doing wrong, but I'm just not clear what. Is there anything I need to start besides the `redis-server` and then running `foreman start`?

**Comment by jegodwin** [comment]
I had some S3 CORS/permission settings that weren't right. I had a pretty good feeling that it was something on my end. Sorry for opening the issue.
