### ISSUE TITLE
Unsupported argument type: Symbol

### ISSUE THREAD

**Issue by yunixon** [erikdahlstrand/shrine-rails-example#49]
rails 5.2
shrine 3.3
sidekiq 5.2

https://github.com/rails/rails/issues/25993

I think best to use String instead Symbol in promote block:

```
Shrine::Attacher.promote_block { Attachment::PromoteJob.perform_later(record, name.to_s, file_data) }
```

**Comment by janko** [comment]
Yeah, makes sense for older versions of Rails. Could you make a PR?
