### ISSUE TITLE
Any blog post about this ?

### ISSUE THREAD

**Issue by ahmgeek** [erikdahlstrand/shrine-rails-example#6]
is there any blog post or article about this example ?

**Comment by erikdahlstrand** [comment]
Hi,

No, not about this this Rails example specifically. But Janko has written a blog post where he introduce Shrine in general.

http://twin.github.io/introducing-shrine/

**Comment by janko-m** [comment]
Although the example apps (Rails, Roda, Lotus) are more for code reading and "proving" that Shrine works, it would probably be useful to add some description in the README what the app does. I'll add it shortly.

**Comment by ahmgeek** [comment]
:+1: that would be awesome, as I want to integrate it in our production.
thanks folks.

**Comment by janko-m** [comment]
I added a description in the README.
