### ISSUE TITLE
Branches demo

### ISSUE THREAD

**Issue by tke578** [erikdahlstrand/shrine-rails-example#68]
Is it possible to have 2 working branches following [direct S3 upload walk through](https://github.com/shrinerb/shrine/wiki/Adding-Direct-S3-Uploads), one with stimulus.js and the other without stimulus.js?

**Comment by janko** [comment]
Keeping mutiple branches up-to-date would be too much maintenance work for me, I'm afraid. When Uppy changes something, it's already a lot for me to have to update the Shrine Roda & Sequel demo, the Rails demo, and the wiki pages.

**Comment by tke578** [comment]
@janko is that wiki still valid? I feel like there is some inconsistencies between the wiki and the repo demo which makes confusing to follow.
