### ISSUE TITLE
Full url for an image-path for displaying the image

### ISSUE THREAD

**Issue by flyingboy007** [erikdahlstrand/shrine-rails-example#8]
The normal `rails` `image_tag` works fine. But how can I get the `full image url` without using the `rails helpers` so that I can use in my `angular` app?

**Comment by janko-m** [comment]
Shrine doesn't ship with any Rails-specific code, so there is nothing extra that Rails helpers give you, so not really sure what is your question. You can always generate the URL either with `photo.image_url` or with `photo.image.url` (`photo.image` is a Shrine::UploadedFile). If you're using the `FileSystem` storage and you want to generate absolute file URLs, you can assign `:host` option when initializing the storage:

```rb
Shrine::Storage::FileSystem.new(host: "http://example.com", **options)
```

Note that usage questions are best asked on the [Shrine Google Group](https://groups.google.com/forum/#!forum/ruby-shrine), GitHub issues should only be used for bug reports.

**Comment by flyingboy007** [comment]
Thank you. It works..
